/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 10/12/2024 06:35:40
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     45000000
#define MX_SYSCLKFreq_VALUE                     45000000
#define MX_HCLKFreq_Value                       45000000
#define MX_FCLKCortexFreq_Value                 45000000
#define MX_CortexFreq_Value                     45000000
#define MX_AHBFreq_Value                        45000000
#define MX_APB1Freq_Value                       22500000
#define MX_APB2Freq_Value                       45000000
#define MX_APB1TimFreq_Value                    45000000
#define MX_APB2TimFreq_Value                    45000000
#define MX_48MHZClocksFreq_Value                45000000
#define MX_EthernetFreq_Value                   16000000
#define MX_I2SClocksFreq_Value                  160000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    16000000

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream6_IRQn */
#define MX_DMA2_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream6_IRQn_Subriority         0

/* NVIC DMA2_Stream1_IRQn */
#define MX_DMA2_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream1_IRQn_Subriority         0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PA8 */
#define MX_S_TIM1_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH1_Pin                       PA8
#define MX_S_TIM1_CH1_GPIOx                     GPIOA
#define MX_S_TIM1_CH1_GPIO_PuPd                 GPIO_PULLUP
#define MX_PENDULUM_ENCODER_A                   S_TIM1_CH1
#define MX_S_TIM1_CH1_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM1_CH1_GPIO_AF                   GPIO_AF1_TIM1

/* Pin PA9 */
#define MX_S_TIM1_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH2_Pin                       PA9
#define MX_S_TIM1_CH2_GPIOx                     GPIOA
#define MX_S_TIM1_CH2_GPIO_PuPd                 GPIO_PULLUP
#define MX_PENDULUM_ENCODER_B                   S_TIM1_CH2
#define MX_S_TIM1_CH2_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM1_CH2_GPIO_AF                   GPIO_AF1_TIM1

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_S_TIM2_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM2_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH2_Pin                       PA1
#define MX_S_TIM2_CH2_GPIOx                     GPIOA
#define MX_S_TIM2_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_MOTOR_PWM                            S_TIM2_CH2
#define MX_S_TIM2_CH2_GPIO_Pin                  GPIO_PIN_1
#define MX_S_TIM2_CH2_GPIO_AF                   GPIO_AF1_TIM2

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* Pin PA6 */
#define MX_S_TIM3_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH1_Pin                       PA6
#define MX_S_TIM3_CH1_GPIOx                     GPIOA
#define MX_S_TIM3_CH1_GPIO_PuPd                 GPIO_PULLUP
#define MX_MOTOR_ENCODER_B                      S_TIM3_CH1
#define MX_S_TIM3_CH1_GPIO_Pin                  GPIO_PIN_6
#define MX_S_TIM3_CH1_GPIO_AF                   GPIO_AF2_TIM3

/* Pin PA7 */
#define MX_S_TIM3_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH2_Pin                       PA7
#define MX_S_TIM3_CH2_GPIOx                     GPIOA
#define MX_S_TIM3_CH2_GPIO_PuPd                 GPIO_PULLUP
#define MX_MOTOR_ENCODER_A                      S_TIM3_CH2
#define MX_S_TIM3_CH2_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM3_CH2_GPIO_AF                   GPIO_AF2_TIM3

/*-------------------------------- USART6     --------------------------------*/

#define MX_USART6                               1

#define MX_USART6_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA12 */
#define MX_USART6_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_RX_Pin                        PA12
#define MX_USART6_RX_GPIOx                      GPIOA
#define MX_USART6_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_UART_DEBUG_RX                        USART6_RX
#define MX_USART6_RX_GPIO_Pin                   GPIO_PIN_12
#define MX_USART6_RX_GPIO_AF                    GPIO_AF8_USART6

/* Pin PA11 */
#define MX_USART6_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_TX_Pin                        PA11
#define MX_USART6_TX_GPIOx                      GPIOA
#define MX_USART6_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_UART_DEBUG_TX                        USART6_TX
#define MX_USART6_TX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART6_TX_GPIO_AF                    GPIO_AF8_USART6

/* DMA Configuration */

/* DMA USART6_RX */
#define MX_USART6_RX_DMA_DMA_Handle
#define MX_USART6_RX_DMA_Instance               DMA2_Stream1
#define MX_USART6_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART6_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART6_RX_DMA_Channel                DMA_CHANNEL_5
#define MX_USART6_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART6_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART6_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART6_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART6_RX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_USART6_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART6_RX_DMA_IpInstance

/* DMA USART6_TX */
#define MX_USART6_TX_DMA_DMA_Handle
#define MX_USART6_TX_DMA_Instance               DMA2_Stream6
#define MX_USART6_TX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART6_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART6_TX_DMA_Channel                DMA_CHANNEL_5
#define MX_USART6_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART6_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART6_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART6_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART6_TX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_USART6_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART6_TX_DMA_IpInstance

/* NVIC Configuration */

/* NVIC USART6_IRQn */
#define MX_USART6_IRQn_interruptPremptionPriority 0
#define MX_USART6_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART6_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA2 */
#define MX_PA2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA2_Pin                              PA2
#define MX_PA2_GPIOx                            GPIOA
#define MX_PA2_PinState                         GPIO_PIN_RESET
#define MX_PA2_GPIO_PuPd                        GPIO_NOPULL
#define MX_MOTOR_DIR_A                          PA2
#define MX_PA2_GPIO_Pin                         GPIO_PIN_2
#define MX_PA2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA3 */
#define MX_PA3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA3_Pin                              PA3
#define MX_PA3_GPIOx                            GPIOA
#define MX_PA3_PinState                         GPIO_PIN_RESET
#define MX_PA3_GPIO_PuPd                        GPIO_NOPULL
#define MX_MOTOR_DIR_B                          PA3
#define MX_PA3_GPIO_Pin                         GPIO_PIN_3
#define MX_PA3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

